title: LVTink's title
author: LVTink herself
email: notarealemail@texasnet.com
description: > # this means to ignore newlines until "baseurl:"
  Here is my text for the blog post. Lots and lots of words. Trying it out to see if it all pulls
  properly. Hopefully we can see all these changes. 
# social links
twitter_username: felix2tink
github_username:  LVTink

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
